### ISSUE TITLE
correct the _listOperator page behavior to display the unfiltered list correctly with pertinent information, let's not forget how it will be used further along in the future

### ISSUE THREAD

**Issue by kiloutyg** [kiloutyg/docauposte2#234]

**Comment by kiloutyg** [comment]
I need to change the first screen to show every operator, ordered by team, then uap, then name alphabet. i will take care of any other views to manage those in the future or i will just give up on it.

**Comment by polangres** [comment]
Have been done, might need further improvment showing the trainer name or list the operators by trainers but at this point has been fully merged in #294
